sonar.host.url=http://localhost:9000
sonar.projectKey=notes-app
sonar.projectName=Notes App

sonar.sources=frontend/src,backend/src

sonar.tests=frontend/tests,backend/tests

sonar.test.inclusions=frontend/tests/**/*.test.js,frontend/tests/**/*.test.jsx,frontend/tests/**/*.test.ts,frontend/tests/**/*.test.tsx,backend/tests/**/*.js

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info,backend/coverage/lcov.info